apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.5.0
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
          volumeMounts:
            - name: kafka-config
              mountPath: /kafka/config/server.properties
              subPath: server.properties
          command:
            - "kafka-server-start"
            - "/kafka/config/server.properties"
          livenessProbe:
            exec:
              command:
                - "kafka-topics"
                - "--bootstrap-server"
                - "localhost:9092"
                - "--list"
            initialDelaySeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - "kafka-topics"
                - "--bootstrap-server"
                - "localhost:9092"
                - "--list"
            initialDelaySeconds: 10
            timeoutSeconds: 5
      volumes:
        - name: kafka-config
          configMap:
            name: kafka-config
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  ports:
    - port: 9092
      targetPort: 9092
  selector:
    app: kafka
  type: ClusterIP


