version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - ./config/zookeeper.properties:/etc/kafka/zookeeper.properties
    command: [ "zookeeper-server-start", "/etc/kafka/zookeeper.properties" ]
    networks:
      - music_stream_network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - ./config/server.properties:/etc/kafka/server.properties
    command: ["kafka-server-start", "/etc/kafka/server.properties"]
    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - music_stream_network
#    restart: on-failure

  producer:
    build:
      context: ./producer
      dockerfile: ./producer/Dockerfile
    container_name: producer
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - music_stream_network
#    restart: on-failure

networks:
  music_stream_network:
    external: true

