name: Deploy Kafka to GCP

on:
  workflow_dispatch: # Only allow manual triggers
  push:
      branches:
      - main

env:
  IMAGE: fake-data-producer-kafka
  DEPLOYMENT_NAME: gke-kafka-producer

jobs:
  #  lint:
  #    uses: ./.github/workflows/lint.yml

  build-and-deploy:
    runs-on: ubuntu-latest
    #    needs: lint

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
          location: ${{ secrets.REGION }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Authenticate Docker with Artifact Registry
        run: gcloud auth configure-docker ${{ secrets.REGION }}-docker.pkg.dev

      - name: Build Docker Image
        working-directory: ./kafka/producer
        run: |
          docker build -t ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.ARTIFACT_REGISTRY_REPO }}/fake-data-producer-kafka:latest .

      - name: Push Docker Image to Artifact Registry
        run: |
          docker push ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.ARTIFACT_REGISTRY_REPO }}/fake-data-producer-kafka:latest

      - name: Set up Kustomize
        working-directory: ./kafka/k8s
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize

      - name: Deploy to GKE
        working-directory: ./kafka/k8s
        run: |
          ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/${{ secrets.GCP_PROJECT_ID }}/$IMAGE:latest
          ./kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/zookeeper
          kubectl rollout status deployment/kafka
          kubectl rollout status deployment/producer
          kubectl get services -o wide