name: Deploy Kafka to GCP

on:
  workflow_dispatch: # Only allow manual triggers
  push:
      branches:
      - main

env:
  IMAGE: fake-data-producer-kafka
  DEPLOYMENT_NAME: gke-kafka-producer

jobs:
  #  lint:
  #    uses: ./.github/workflows/lint.yml

  build-and-deploy:
    runs-on: ubuntu-latest
    #    needs: lint

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authenticate Docker with Artifact Registry
        run: gcloud auth configure-docker ${{ secrets.REGION }}-docker.pkg.dev

      - name: Build Docker Image
        working-directory: ./kafka/producer
        run: |
          docker build -t ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.ARTIFACT_REGISTRY_REPO }}/fake-data-producer-kafka:latest .

      - name: Push Docker Image to Artifact Registry
        run: |
          docker push ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.ARTIFACT_REGISTRY_REPO }}/fake-data-producer-kafka:latest

      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize

      - name: Install gke-gcloud-auth-plugin
        run: |
          sudo apt-get update
          sudo apt-get install apt-transport-https ca-certificates gnupg
          sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

      - name: Deploy to GKE
        working-directory: ./k8s
        env:
          KUBECONFIG: /tmp/kubeconfig
        run: |
          ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/${{ secrets.GCP_PROJECT_ID }}/$IMAGE:latest
          ./kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/zookeeper
          kubectl rollout status deployment/kafka
          kubectl rollout status deployment/producer
          kubectl get services -o wide
          

#      - name: Deploy to GKE
#        working-directory: ./kafka
#        env:
#          KUBECONFIG: /tmp/kubeconfig
#        run: |
#          gcloud container clusters get-credentials ${{ secrets.CLUSTER_NAME }} --region ${{ secrets.REGION }}
#          kubectl apply -f k8s/zookeeper-deployment.yaml
#          kubectl apply -f k8s/kafka-deployment.yaml
#          kubectl apply -f k8s/producer-deployment.yaml
